"""initial schema

Revision ID: 0e84770350f6
Revises: 
Create Date: 2026-08-11 23:23:28.897541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e84770350f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('households',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_households_id'), 'households', ['id'], unique=False)
    op.create_table('swiggy_client_registrations',
    sa.Column('redirect_uri', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('client_secret', sa.String(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('redirect_uri')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('auth_provider', sa.String(), nullable=False),
    sa.Column('swiggy_user_ref', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_swiggy_user_ref'), 'users', ['swiggy_user_ref'], unique=True)
    op.create_table('delivery_addresses',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('address_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('display_text', sa.String(), nullable=False),
    sa.Column('last_selected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'address_id')
    )
    op.create_table('grocery_lists',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('household_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grocery_lists_id'), 'grocery_lists', ['id'], unique=False)
    op.create_table('household_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('household_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dietary_preference', sa.String(), nullable=False),
    sa.Column('allergies', sa.JSON(), nullable=False),
    sa.Column('calorie_target', sa.Integer(), nullable=True),
    sa.Column('protein_target', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_household_members_id'), 'household_members', ['id'], unique=False)
    op.create_table('instamart_cart_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('household_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('swiggy_cart_meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instamart_cart_sessions_id'), 'instamart_cart_sessions', ['id'], unique=False)
    op.create_table('order_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('address_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('selected_restaurant_id', sa.String(), nullable=True),
    sa.Column('selected_item_id', sa.String(), nullable=True),
    sa.Column('cart_snapshot', sa.JSON(), nullable=True),
    sa.Column('selected_item_nutrition', sa.JSON(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_sessions_id'), 'order_sessions', ['id'], unique=False)
    op.create_table('pantry_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('household_id', sa.String(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('stock_level', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('is_bulk', sa.Boolean(), nullable=False),
    sa.Column('bulk_use_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pantry_items_id'), 'pantry_items', ['id'], unique=False)
    op.create_index(op.f('ix_pantry_items_item_name'), 'pantry_items', ['item_name'], unique=False)
    op.create_table('recipe_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('household_id', sa.String(), nullable=False),
    sa.Column('recipe_name', sa.String(), nullable=False),
    sa.Column('ingredients', sa.JSON(), nullable=False),
    sa.Column('planned_for_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_plans_id'), 'recipe_plans', ['id'], unique=False)
    op.create_table('swiggy_tokens',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('encrypted_access_token', sa.LargeBinary(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('protein_target', sa.Integer(), nullable=False),
    sa.Column('calorie_target', sa.Integer(), nullable=False),
    sa.Column('diet_preference', sa.String(), nullable=False),
    sa.Column('allergies', sa.JSON(), nullable=False),
    sa.Column('dislikes', sa.JSON(), nullable=False),
    sa.Column('favorite_cuisines', sa.JSON(), nullable=False),
    sa.Column('fitness_goal', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('activity_level', sa.String(), nullable=False),
    sa.Column('meal_budget_default', sa.Integer(), nullable=False),
    sa.Column('preferred_meal_times', sa.JSON(), nullable=False),
    sa.Column('spice_tolerance', sa.String(), nullable=False),
    sa.Column('priority_weights', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('weight_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weight_entries_entry_date'), 'weight_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_weight_entries_id'), 'weight_entries', ['id'], unique=False)
    op.create_index(op.f('ix_weight_entries_user_id'), 'weight_entries', ['user_id'], unique=False)
    op.create_table('grocery_list_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('grocery_list_id', sa.String(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('is_purchased', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['grocery_list_id'], ['grocery_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grocery_list_items_id'), 'grocery_list_items', ['id'], unique=False)
    op.create_index(op.f('ix_grocery_list_items_item_name'), 'grocery_list_items', ['item_name'], unique=False)
    op.create_table('nutrition_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('meal_name', sa.String(), nullable=False),
    sa.Column('restaurant_name', sa.String(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_estimated', sa.Boolean(), nullable=False),
    sa.Column('order_session_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_session_id'], ['order_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_session_id')
    )
    op.create_index(op.f('ix_nutrition_entries_entry_date'), 'nutrition_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_nutrition_entries_id'), 'nutrition_entries', ['id'], unique=False)
    op.create_index(op.f('ix_nutrition_entries_user_id'), 'nutrition_entries', ['user_id'], unique=False)
    op.create_table('order_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_session_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_session_id'], ['order_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_events_id'), 'order_events', ['id'], unique=False)
    op.create_table('order_feedbacks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('order_session_id', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('filling', sa.String(), nullable=True),
    sa.Column('spicy', sa.String(), nullable=True),
    sa.Column('again', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_session_id'], ['order_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_session_id')
    )
    op.create_index(op.f('ix_order_feedbacks_id'), 'order_feedbacks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_feedbacks_id'), table_name='order_feedbacks')
    op.drop_table('order_feedbacks')
    op.drop_index(op.f('ix_order_events_id'), table_name='order_events')
    op.drop_table('order_events')
    op.drop_index(op.f('ix_nutrition_entries_user_id'), table_name='nutrition_entries')
    op.drop_index(op.f('ix_nutrition_entries_id'), table_name='nutrition_entries')
    op.drop_index(op.f('ix_nutrition_entries_entry_date'), table_name='nutrition_entries')
    op.drop_table('nutrition_entries')
    op.drop_index(op.f('ix_grocery_list_items_item_name'), table_name='grocery_list_items')
    op.drop_index(op.f('ix_grocery_list_items_id'), table_name='grocery_list_items')
    op.drop_table('grocery_list_items')
    op.drop_index(op.f('ix_weight_entries_user_id'), table_name='weight_entries')
    op.drop_index(op.f('ix_weight_entries_id'), table_name='weight_entries')
    op.drop_index(op.f('ix_weight_entries_entry_date'), table_name='weight_entries')
    op.drop_table('weight_entries')
    op.drop_table('user_profiles')
    op.drop_table('swiggy_tokens')
    op.drop_index(op.f('ix_recipe_plans_id'), table_name='recipe_plans')
    op.drop_table('recipe_plans')
    op.drop_index(op.f('ix_pantry_items_item_name'), table_name='pantry_items')
    op.drop_index(op.f('ix_pantry_items_id'), table_name='pantry_items')
    op.drop_table('pantry_items')
    op.drop_index(op.f('ix_order_sessions_id'), table_name='order_sessions')
    op.drop_table('order_sessions')
    op.drop_index(op.f('ix_instamart_cart_sessions_id'), table_name='instamart_cart_sessions')
    op.drop_table('instamart_cart_sessions')
    op.drop_index(op.f('ix_household_members_id'), table_name='household_members')
    op.drop_table('household_members')
    op.drop_index(op.f('ix_grocery_lists_id'), table_name='grocery_lists')
    op.drop_table('grocery_lists')
    op.drop_table('delivery_addresses')
    op.drop_index(op.f('ix_users_swiggy_user_ref'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('swiggy_client_registrations')
    op.drop_index(op.f('ix_households_id'), table_name='households')
    op.drop_table('households')
    # ### end Alembic commands ###
