"""add micronutrients to nutrition_entries

Revision ID: 5b2a44f85c2e
Revises: e9de3c955a40
Create Date: 2026-08-22 00:52:59.216128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b2a44f85c2e'
down_revision: Union[str, Sequence[str], None] = 'e9de3c955a40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrition_entries', sa.Column('micronutrients', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nutrition_entries', 'micronutrients')
    # ### end Alembic commands ###
