"""add mcp_mode to order_sessions

Revision ID: e9de3c955a40
Revises: 0e84770350f6
Create Date: 2026-08-12 00:58:35.717683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9de3c955a40'
down_revision: Union[str, Sequence[str], None] = '0e84770350f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_sessions', sa.Column('mcp_mode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_sessions', 'mcp_mode')
    # ### end Alembic commands ###
